CREATE TABLE `alimenti` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `nome_alimento` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Nome Alimento',
  `categoria` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Categoria',
  `codice_alimento` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Codice Alimento',
  `parte_edibile` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Parte Edibile',
  `porzione` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Porzione',
  `acqua_g` decimal(10,3) DEFAULT NULL COMMENT 'Acqua (g)',
  `energia_kcal` decimal(10,3) DEFAULT NULL COMMENT 'Energia (kcal)',
  `energia_kj` decimal(10,3) DEFAULT NULL COMMENT 'Energia (kJ)',
  `proteine_g` decimal(10,3) DEFAULT NULL COMMENT 'Proteine (g)',
  `lipidi_g` decimal(10,3) DEFAULT NULL COMMENT 'Lipidi (g)',
  `carboidrati_disponibili_g` decimal(10,3) DEFAULT NULL COMMENT 'Carboidrati disponibili (g)',
  `amido_g` decimal(10,3) DEFAULT NULL COMMENT 'Amido (g)',
  `zuccheri_solubili_g` decimal(10,3) DEFAULT NULL COMMENT 'Zuccheri solubili (g)',
  `alcool_g` decimal(10,3) DEFAULT NULL COMMENT 'Alcool (g)',
  `fibra_totale_g` decimal(10,3) DEFAULT NULL COMMENT 'Fibra totale (g)',
  `sodio_mg` decimal(10,3) DEFAULT NULL COMMENT 'Sodio (mg)',
  `potassio_mg` decimal(10,3) DEFAULT NULL COMMENT 'Potassio (mg)',
  `calcio_mg` decimal(10,3) DEFAULT NULL COMMENT 'Calcio (mg)',
  `fosforo_mg` decimal(10,3) DEFAULT NULL COMMENT 'Fosforo (mg)',
  `ferro_mg` decimal(10,3) DEFAULT NULL COMMENT 'Ferro (mg)',
  `vitamina_c_mg` decimal(10,3) DEFAULT NULL COMMENT 'Vitamina C (mg)',
  `vitamina_a_retinolo_eq_mcg` decimal(10,3) DEFAULT NULL COMMENT 'Vitamina A retinolo equivalente (µg)',
  `acido_fitico_g` decimal(10,3) DEFAULT NULL COMMENT 'Acido fitico (g)',
  `colesterolo_mg` decimal(10,3) DEFAULT NULL COMMENT 'Colesterolo (mg)',
  `magnesio_mg` decimal(10,3) DEFAULT NULL COMMENT 'Magnesio (mg)',
  `rame_mg` decimal(10,3) DEFAULT NULL COMMENT 'Rame (mg)',
  `zinco_mg` decimal(10,3) DEFAULT NULL COMMENT 'Zinco (mg)',
  `acidi_grassi_saturi_pct` decimal(10,3) DEFAULT NULL COMMENT 'Acidi grassi Saturi (%)',
  `acidi_grassi_monoinsaturi_pct` decimal(10,3) DEFAULT NULL COMMENT 'Acidi grassi Monoinsaturi (%)',
  `acidi_grassi_polinsaturi_pct` decimal(10,3) DEFAULT NULL COMMENT 'Acidi grassi Polinsaturi (%)',
  `rapporto_polinsaturi_saturi` decimal(10,3) DEFAULT NULL COMMENT 'Polinsatuti/Saturi',
  `indice_chimico` decimal(10,3) DEFAULT NULL COMMENT 'Indice Chimico',
  `aminoacido_limitante` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Aminoacido limitante',
  `saccarosio_g` decimal(10,3) DEFAULT NULL COMMENT 'Saccarosio (g)',
  `glucosio_g` decimal(10,3) DEFAULT NULL COMMENT 'Glucosio (g)',
  `fruttosio_g` decimal(10,3) DEFAULT NULL COMMENT 'Fruttosio (g)',
  `manganese_mg` decimal(10,3) DEFAULT NULL COMMENT 'Manganese (mg)',
  `vitamina_b6_mg` decimal(10,3) DEFAULT NULL COMMENT 'Vitamina B6 (mg)',
  `vitamina_b12_mcg` decimal(10,3) DEFAULT NULL COMMENT 'Vitamina B12 (µg)',
  `retinolo_mcg` decimal(10,3) DEFAULT NULL COMMENT 'Retinolo (µg)',
  `carotene_beta_mcg` decimal(10,3) DEFAULT NULL COMMENT 'Carotene beta (µg)',
  `vitamina_d_mcg` decimal(10,3) DEFAULT NULL COMMENT 'Vitamina D (µg)',
  `polifenoli_mg` decimal(10,3) DEFAULT NULL COMMENT 'Polifenoli (mg)',
  `fruttoligosaccaridi_g` decimal(10,3) DEFAULT NULL COMMENT 'Fruttoligosaccaridi (g)',
  `informazioni` text COLLATE utf8mb4_unicode_ci COMMENT 'Informazioni',
  `allergeni` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Elenco allergeni maggiori (Reg. UE 1169/2011) separati da ; ',
  `gruppo_alimentare_crea` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Gruppo alimentare secondo la piramide alimentare CREA (ex INRAN)',
  `vegano` tinyint(1) DEFAULT NULL COMMENT 'TRUE se l''alimento e'' idoneo a una dieta vegana',
  `vegetariano` tinyint(1) DEFAULT NULL COMMENT 'TRUE se l''alimento e'' idoneo a una dieta vegetariana',
  `senza_glutine` tinyint(1) DEFAULT NULL COMMENT 'TRUE se l''alimento non contiene glutine',
  `indice_glicemico` decimal(5,1) DEFAULT NULL COMMENT 'Indice glicemico (scala glucosio=100), da tabelle pubblicate',
  `carico_glicemico` decimal(5,1) DEFAULT NULL COMMENT 'Carico glicemico riferito alla porzione standard indicata in "porzione"',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_codice_alimento` (`codice_alimento`),
  KEY `idx_categoria` (`categoria`),
  KEY `idx_nome_alimento` (`nome_alimento`)
) ENGINE=InnoDB AUTO_INCREMENT=850 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tabelle di composizione degli alimenti - CREA (per 100 g di parte edibile)';
