-- =====================================================================================
-- DATI — Smartfood: Porzioni e frequenze di consumo
-- Da eseguire DOPO smartfood_schema.sql, nello stesso database.
-- =====================================================================================

INSERT INTO `smartfood_porzioni_frequenze`
  (`ordine`, `frequenza_consumo`, `gruppo_alimenti`, `alimento`, `porzione_standard`,
   `porzione_quantita`, `porzione_unita`, `corrispondenza`, `quante_volte`, `consiglio_smart`)
VALUES

-- ================================= GIORNALIERA ======================================
(1,  'giornaliera', 'VERDURE E ORTAGGI', 'Verdure e ortaggi', '200 g', 200, 'g',
  '2-3 pomodori, 3-4 carote, 1 peperone, 1 finocchio, 2 carciofi, 2-3 zucchine, 7-10 ravanelli, 1-2 cipolle, verdure cotte (spinaci, bieta, broccoli, cavolfiore, melanzane etc.) 1/2 piatto',
  '1-2 porzioni a pasto',
  'Prediligi prodotti di stagione, variando tipologia, colore e alternando il consumo di verdure crude a quelle cotte.'),
(2,  'giornaliera', 'VERDURE E ORTAGGI', 'Insalate a foglia', '80 g', 80, 'g',
  '1 scodella grande',
  '1-2 porzioni a pasto',
  'Prediligi prodotti di stagione, variando tipologia, colore e alternando il consumo di verdure crude a quelle cotte.'),

(3,  'giornaliera', 'FRUTTA FRESCA ED ESSICCATA', 'Frutta fresca', '150 g', 150, 'g',
  '1 frutto medio, 2-3 frutti piccoli',
  '2-3 porzioni al giorno (compresa, a piacere, 1 porzione di frutta essiccata)',
  'Prediligi prodotti di stagione, variando tipologia e colore.'),
(4,  'giornaliera', 'FRUTTA FRESCA ED ESSICCATA', 'Frutta essiccata', '30 g', 30, 'g',
  '3 albicocche/fichi secchi/datteri, 2 cucchiai rasi di uvetta, 2 prugne secche',
  '2-3 porzioni al giorno (compresa, a piacere, 1 porzione di frutta essiccata)',
  'Prediligi prodotti di stagione, variando tipologia e colore.'),

(5,  'giornaliera', 'FRUTTA SECCA A GUSCIO E SEMI OLEOSI', 'Noci, nocciole, pistacchi, mandorle, semi di lino, sesamo, zucca etc.', '30 g', 30, 'g',
  '7-8 noci, 15-20 mandorle/nocciole, 4 cucchiai rasi di semi oleosi',
  '1 porzione al giorno',
  'Utilizza la frutta secca a guscio come spuntino o fine pasto, o come ingrediente delle tue preparazioni. I semi oleosi sono un ottimo arricchimento per insalate e panature.'),

(6,  'giornaliera', 'CEREALI E DERIVATI', 'Pasta, cous cous, riso, mais, farro, orzo, quinoa, farine etc.', '80 g', 80, 'g',
  '50 penne/fusilli, 6-8 cucchiai di pastina, 4 cucchiai di riso, 6-8 cucchiai di farina',
  '1-2 porzioni a pasto',
  'Scegli quanto più possibile la versione integrale di pasta, pane, cereali e altri prodotti derivati.'),
(7,  'giornaliera', 'CEREALI E DERIVATI', 'Pane', '50 g', 50, 'g',
  '1 panino piccolo, 1/2 ciabattina, 1 fetta media, 1/5 di baguette, 1/2 piadina, 1 chapati, 1 pita, 1 tortilla media',
  '1-2 porzioni a pasto',
  'Scegli quanto più possibile la versione integrale di pasta, pane, cereali e altri prodotti derivati.'),
(8,  'giornaliera', 'CEREALI E DERIVATI', 'Cereali per la colazione e fette biscottate', '30 g', 30, 'g',
  '6-8 cucchiai di fiocchi di mais, 3 cucchiai di muesli, 3-4 fette biscottate',
  '1-2 porzioni al giorno',
  'Scegli quanto più possibile la versione integrale di pasta, pane, cereali e altri prodotti derivati.'),

(9,  'giornaliera', 'LATTE E YOGURT', 'Latte vaccino', '125 ml', 125, 'ml',
  '1 bicchiere piccolo, 1/2 tazza media',
  '2-3 porzioni al giorno',
  'Preferisci le versioni al naturale, senza aggiunta di zuccheri.'),
(10, 'giornaliera', 'LATTE E YOGURT', 'Yogurt vaccino e altri latti fermentati', '125 g', 125, 'g',
  '1 vasetto standard',
  '2-3 porzioni al giorno',
  'Preferisci le versioni al naturale, senza aggiunta di zuccheri.'),
(11, 'giornaliera', 'LATTE E YOGURT', 'Alternative vegetali a latte e yogurt, a base di soia', '125 ml/g', 125, 'ml/g',
  NULL,
  '2-3 porzioni al giorno',
  'Preferisci le versioni al naturale, senza aggiunta di zuccheri.'),

(12, 'giornaliera', 'CONDIMENTI', 'Olio extravergine d''oliva (olio EVO)', '9 g', 9, 'g',
  '1 cucchiaio (10 ml)',
  '2-3 porzioni a pasto',
  'L''olio EVO deve essere la scelta principale, in alternativa oli di semi solo spremuti a freddo.'),
(13, 'giornaliera', 'CONDIMENTI', 'Erbe aromatiche, spezie, succo e scorza di agrumi', 'a piacere', NULL, NULL,
  NULL,
  'Ogni giorno',
  'Arricchisci i tuoi piatti con spezie, erbe aromatiche, succo e scorza di agrumi, per dare sapore, colore e profumo ai tuoi piatti e per ridurre o eliminare il sale.'),

(14, 'giornaliera', 'BEVANDE CALDE NON ZUCCHERATE', 'Caffè/orzo', '30 ml tazzina tipo bar / 50 ml tazzina tipo moka', NULL, 'ml',
  '1 tazzina da bar/moka',
  'A piacere',
  'Soglia di sicurezza EFSA per le bevande contenenti caffeina: fino a 400 mg al giorno per gli adulti sani, 200 mg per le donne in gravidanza e in allattamento. Esempi di quantitativi di caffeina: caffè espresso circa 80 mg, tè in tazza circa 50 mg, caffè americano circa 90 mg.'),
(15, 'giornaliera', 'BEVANDE CALDE NON ZUCCHERATE', 'Tè e tisane', '200 ml', 200, 'ml',
  '1 tazza',
  'A piacere',
  'Soglia di sicurezza EFSA per le bevande contenenti caffeina: fino a 400 mg al giorno per gli adulti sani, 200 mg per le donne in gravidanza e in allattamento. Esempi di quantitativi di caffeina: caffè espresso circa 80 mg, tè in tazza circa 50 mg, caffè americano circa 90 mg.'),

(16, 'giornaliera', 'ACQUA', 'Acqua', '200 ml', 200, 'ml',
  '1 bicchiere medio',
  'Circa 8-10 bicchieri al giorno',
  'Da assumere in base alle esigenze fisiologiche. L''acqua del rubinetto è la scelta più sostenibile, l''acqua erogata dagli acquedotti italiani è generalmente sicura e di ottima qualità.'),

-- ================================= SETTIMANALE ======================================
(17, 'settimanale', 'LEGUMI', 'Legumi freschi o in scatola o surgelati', '150 g', 150, 'g',
  '1/2 piatto, una scatola piccola, 7-8 cucchiai',
  '3-4 o più porzioni a settimana',
  'Fanno parte delle porzioni settimanali di legumi anche le paste di legumi 100% e i derivati della soia come il tofu, il tempeh o i burger di soia. Se utilizzata come alternativa alla pasta di semola si può fare riferimento a una porzione da 80 g, da abbinare a una porzione di pane e da condire, preferibilmente, con un sugo a base di verdure.'),
(18, 'settimanale', 'LEGUMI', 'Legumi secchi', '50 g', 50, 'g',
  '3-4 cucchiai',
  '3-4 o più porzioni a settimana',
  'Fanno parte delle porzioni settimanali di legumi anche le paste di legumi 100% e i derivati della soia come il tofu, il tempeh o i burger di soia. Se utilizzata come alternativa alla pasta di semola si può fare riferimento a una porzione da 80 g, da abbinare a una porzione di pane e da condire, preferibilmente, con un sugo a base di verdure.'),
(19, 'settimanale', 'LEGUMI', 'Pasta di legumi (100%)', '50 g', 50, 'g',
  NULL,
  '3-4 o più porzioni a settimana',
  'Fanno parte delle porzioni settimanali di legumi anche le paste di legumi 100% e i derivati della soia come il tofu, il tempeh o i burger di soia. Se utilizzata come alternativa alla pasta di semola si può fare riferimento a una porzione da 80 g, da abbinare a una porzione di pane e da condire, preferibilmente, con un sugo a base di verdure.'),
(20, 'settimanale', 'LEGUMI', 'Tofu/tempeh', '100 g', 100, 'g',
  NULL,
  '3-4 o più porzioni a settimana',
  'Fanno parte delle porzioni settimanali di legumi anche le paste di legumi 100% e i derivati della soia come il tofu, il tempeh o i burger di soia. Se utilizzata come alternativa alla pasta di semola si può fare riferimento a una porzione da 80 g, da abbinare a una porzione di pane e da condire, preferibilmente, con un sugo a base di verdure.'),
(21, 'settimanale', 'LEGUMI', 'Burger a base di soia o legumi', '100 g', 100, 'g',
  NULL,
  '3-4 o più porzioni a settimana',
  'Fanno parte delle porzioni settimanali di legumi anche le paste di legumi 100% e i derivati della soia come il tofu, il tempeh o i burger di soia. Se utilizzata come alternativa alla pasta di semola si può fare riferimento a una porzione da 80 g, da abbinare a una porzione di pane e da condire, preferibilmente, con un sugo a base di verdure.'),

(22, 'settimanale', 'PESCE', 'Pesce, molluschi, crostacei freschi o surgelati', '150 g', 150, 'g',
  '1 pesce piccolo, 1 filetto medio, 25 cozze, 3 gamberoni, 20 gamberetti',
  '3-4 porzioni a settimana',
  'Scegli pesce azzurro, fonte di acidi grassi omega-3, almeno 1-2 volte a settimana. Il pesce conservato può essere consumato 1 volta a settimana.'),
(23, 'settimanale', 'PESCE', 'Pesce, molluschi, crostacei conservati', '50 g', 50, 'g',
  '1 scatola piccola di tonno sgocciolato, 4-5 fette di salmone affumicato',
  '3-4 porzioni a settimana',
  'Scegli pesce azzurro, fonte di acidi grassi omega-3, almeno 1-2 volte a settimana. Il pesce conservato può essere consumato 1 volta a settimana.'),

(24, 'settimanale', 'FORMAGGI', 'Formaggi freschi (<=25% di grassi)', '100 g', 100, 'g',
  '1 mozzarella piccola, 4 ciliegine di mozzarella, 4 fettine tipo formaggio fuso, 2 cucchiai e 1/2 di formaggio spalmabile',
  '2-3 porzioni a settimana',
  'Preferisci i formaggi freschi e magri (<=25% di grassi) a quelli stagionati. Per le alternative vegetali al formaggio: verifica i valori nutrizionali in etichetta e scegli i prodotti con meno sale possibile e con un quantitativo di proteine paragonabile ai formaggi di origine animale.'),
(25, 'settimanale', 'FORMAGGI', 'Ricotta', '150 g', 150, 'g',
  NULL,
  '2-3 porzioni a settimana',
  'Preferisci i formaggi freschi e magri (<=25% di grassi) a quelli stagionati. Per le alternative vegetali al formaggio: verifica i valori nutrizionali in etichetta e scegli i prodotti con meno sale possibile e con un quantitativo di proteine paragonabile ai formaggi di origine animale.'),
(26, 'settimanale', 'FORMAGGI', 'Altri formaggi (>25% di grassi)', '50 g', 50, 'g',
  '2 fettine tipo formaggio fuso, 2 cubetti e 1/2 di parmigiano, 2 cucchiai di formaggio cremoso, 2 formaggini e 1/2',
  '2-3 porzioni a settimana',
  'Preferisci i formaggi freschi e magri (<=25% di grassi) a quelli stagionati. Per le alternative vegetali al formaggio: verifica i valori nutrizionali in etichetta e scegli i prodotti con meno sale possibile e con un quantitativo di proteine paragonabile ai formaggi di origine animale.'),
(27, 'settimanale', 'FORMAGGI', 'Formaggio grattugiato', '10 g', 10, 'g',
  '1 cucchiaio (1/5 di porzione)',
  '2-3 porzioni a settimana',
  'Preferisci i formaggi freschi e magri (<=25% di grassi) a quelli stagionati. Per le alternative vegetali al formaggio: verifica i valori nutrizionali in etichetta e scegli i prodotti con meno sale possibile e con un quantitativo di proteine paragonabile ai formaggi di origine animale.'),
(28, 'settimanale', 'FORMAGGI', 'Alternative vegetali al formaggio', '100 g', 100, 'g',
  NULL,
  '2-3 porzioni a settimana',
  'Preferisci i formaggi freschi e magri (<=25% di grassi) a quelli stagionati. Per le alternative vegetali al formaggio: verifica i valori nutrizionali in etichetta e scegli i prodotti con meno sale possibile e con un quantitativo di proteine paragonabile ai formaggi di origine animale.'),

(29, 'settimanale', 'UOVA', 'Uova', '50 g', 50, 'g',
  '1 uovo di gallina',
  '2-4 uova a settimana',
  'Le uova possono essere consumate come fonte proteica di un pranzo o una cena, ma anche a colazione, in sostituzione di latte e latticini, per un''alternativa salata.'),

(30, 'settimanale', 'CARNE', 'Carne bianca fresca o surgelata (pollo, tacchino e coniglio)', '100 g', 100, 'g',
  '1 fetta di petto di pollo o tacchino, 1 piccola coscia di pollo',
  '1-2 porzioni a settimana',
  'Preferisci la carne bianca, limita quella rossa ed evita la carne lavorata. Per le alternative vegetali alla carne: verifica i valori nutrizionali in etichetta e scegli i prodotti con meno sale possibile e con un quantitativo di proteine paragonabile alla carne.'),
(31, 'settimanale', 'CARNE', 'Alternative vegetali alla carne (burger vegetali, seitan etc.)', '100 g', 100, 'g',
  NULL,
  '1-2 porzioni a settimana',
  'Preferisci la carne bianca, limita quella rossa ed evita la carne lavorata. Per le alternative vegetali alla carne: verifica i valori nutrizionali in etichetta e scegli i prodotti con meno sale possibile e con un quantitativo di proteine paragonabile alla carne.'),
(32, 'settimanale', 'CARNE', 'Carne rossa fresca o surgelata (bovina, ovina, suina ed equina)', '100 g', 100, 'g',
  '1 fettina, 1 svizzera, 4-5 pezzi di spezzatino, 1 salsiccia',
  '0-1 porzione a settimana',
  'Preferisci la carne bianca, limita quella rossa ed evita la carne lavorata. Per le alternative vegetali alla carne: verifica i valori nutrizionali in etichetta e scegli i prodotti con meno sale possibile e con un quantitativo di proteine paragonabile alla carne.'),

(33, 'settimanale', 'TUBERI', 'Patate e altri tuberi', '200 g', 200, 'g',
  '2 patate piccole',
  '1-2 porzioni a settimana',
  'Le patate sono da considerarsi una fonte di carboidrati al pari di pasta e pane, non vanno utilizzate come contorno ma in sostituzione del primo piatto.'),

(34, 'settimanale', 'MARMELLATA', 'Marmellate e composte', '20 g', 20, 'g',
  '2 cucchiaini colmi',
  'Circa 3 volte alla settimana per un consumo a colazione con il pane integrale o le fette biscottate, da alternare ad altre tipologie di colazione',
  'Scegli marmellate con un contenuto di zuccheri uguale o inferiore al 35% e con una percentuale di frutta di almeno il 70%. Sono da evitare marmellate e composte dolcificate con edulcoranti.'),

-- ================================= OCCASIONALE ======================================
(35, 'occasionale', 'DOLCI', 'Torte e gelati', '70 g', 70, 'g',
  '1 fetta, 1 coppetta',
  'Consumo occasionale',
  'Modera il consumo di dolci e prodotti da forno dolci. Per i biscotti, scegli quelli integrali, con un buon apporto di fibra, e con il minor contenuto di zuccheri e sale possibile, evitando i prodotti con edulcoranti.'),
(36, 'occasionale', 'DOLCI', 'Prodotti da forno dolci (brioche, croissant, cornetti, biscotti, merendine, barrette etc.)', '30 g', 30, 'g',
  '1 brioche piccola, 1/2 brioche grande, 2-3 biscotti, 1 merendina, 1 barretta',
  'Consumo occasionale',
  'Modera il consumo di dolci e prodotti da forno dolci. Per i biscotti, scegli quelli integrali, con un buon apporto di fibra, e con il minor contenuto di zuccheri e sale possibile, evitando i prodotti con edulcoranti.'),

(37, 'occasionale', 'ZUCCHERI', 'Zucchero', '5 g', 5, 'g',
  '1 cucchiaino raso',
  'Consumo occasionale',
  'Le linee guida nazionali ed internazionali raccomandano di assumere una quantità di zuccheri non superiore al 10% dell''energia giornaliera. Non c''è alcuna differenza sostanziale tra zucchero bianco, di canna o miele, l''importante è consumarne il meno possibile.'),
(38, 'occasionale', 'ZUCCHERI', 'Miele', '10 g', 10, 'g',
  '1 cucchiaino colmo',
  'Consumo occasionale',
  'Le linee guida nazionali ed internazionali raccomandano di assumere una quantità di zuccheri non superiore al 10% dell''energia giornaliera. Non c''è alcuna differenza sostanziale tra zucchero bianco, di canna o miele, l''importante è consumarne il meno possibile.'),

(39, 'occasionale', 'BEVANDE ANALCOLICHE', 'Succhi di frutta, tè freddo e altre bibite zuccherate gassate e non (cola, aranciata etc.)', '200/300 ml', NULL, 'ml',
  '1 bicchiere medio/brick/bottiglietta, 1 lattina',
  'Consumo occasionale',
  'I succhi di frutta non devono essere considerati sostituti della frutta. Ai pasti consumare solo acqua.'),

(40, 'occasionale', 'SNACK SALATI', 'Patatine, pop-corn, salatini etc.', '25 g', 25, 'g',
  '1 bustina monoporzione',
  'Consumo occasionale',
  'Modera il consumo di questi prodotti, spesso ultraprocessati e molto ricchi in sale.'),

(41, 'occasionale', 'SOSTITUTI DEL PANE', 'Sostituti del pane (crackers, grissini, friselle, tarallini, gallette etc.)', '30 g', 30, 'g',
  '5 crackers, 1 frisella, 3-4 tarallini, 3-4 gallette',
  'Consumo occasionale',
  'Modera il consumo di questi prodotti, spesso molto ricchi in sale. Preferisci le versioni integrali perché più ricche in fibra.'),

-- =================================== EVITARE ========================================
(42, 'evitare', 'CARNI LAVORATE', 'Salumi', '50 g', 50, 'g',
  '3-4 fette di prosciutto, 5-6 fette di salame/bresaola, 2 fette di mortadella',
  'Da evitare',
  'Le linee guida internazionali per la prevenzione oncologica e cardiovascolare raccomandano di limitare fortemente il consumo di carni lavorate.'),

(43, 'evitare', 'BEVANDE ALCOLICHE', 'Vino', '125 ml', 125, 'ml',
  '1 bicchiere da vino',
  'Da evitare',
  'Le linee guida internazionali per la prevenzione oncologica e cardiovascolare raccomandano di limitare fortemente il consumo di qualsiasi tipo di bevanda alcolica.'),
(44, 'evitare', 'BEVANDE ALCOLICHE', 'Birra', '330 ml', 330, 'ml',
  '1 lattina media',
  'Da evitare',
  'Le linee guida internazionali per la prevenzione oncologica e cardiovascolare raccomandano di limitare fortemente il consumo di qualsiasi tipo di bevanda alcolica.'),
(45, 'evitare', 'BEVANDE ALCOLICHE', 'Superalcolici', '40 ml', 40, 'ml',
  '1 bicchierino da superalcolico',
  'Da evitare',
  'Le linee guida internazionali per la prevenzione oncologica e cardiovascolare raccomandano di limitare fortemente il consumo di qualsiasi tipo di bevanda alcolica.');
